# Generated by Django 2.0.6 on 2019-01-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCardInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, null=True)),
                ('bank', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'user_banks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('telephone', models.IntegerField(null=True)),
                ('user_email', models.CharField(max_length=50, null=True)),
                ('user_idcard', models.CharField(max_length=20, null=True)),
                ('user_session', models.CharField(max_length=50, null=True)),
                ('user_kind', models.IntegerField(default=1)),
                ('user_age', models.IntegerField(null=True)),
                ('user_sex', models.CharField(max_length=5, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_code', models.CharField(max_length=15)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('moeny', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'user_products',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_product',
            field=models.ManyToManyField(through='user.UserProduct', to='home_page.Products'),
        ),
        migrations.AddField(
            model_name='bankcardinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
