# Generated by Django 2.0.6 on 2019-01-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('p_name', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('earning', models.FloatField(blank=True, null=True)),
                ('earn_7d', models.FloatField(blank=True, null=True)),
                ('earn_14d', models.FloatField(blank=True, null=True)),
                ('earn_28d', models.FloatField(blank=True, null=True)),
                ('earn_35d', models.FloatField(blank=True, null=True)),
                ('path_1m', models.FloatField(blank=True, null=True)),
                ('path_3m', models.FloatField(blank=True, null=True)),
                ('path_6m', models.FloatField(blank=True, null=True)),
                ('path_1y', models.FloatField(blank=True, null=True)),
                ('strat_money', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
